name: numandev
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  go_router: ^12.1.1
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/